### ISSUE TITLE
运行yarn start报错，await被识别为保留关键字报错

### ISSUE THREAD

**Issue by winglight** [buxuku/VideoSubtitleGenerator#10]
```
yarn run v1.22.22
$ node index.js
file:///Users/work/opensource/VideoSubtitleGenerator/index.js:12
await installWhisper();
^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:140:18)
    at async link (internal/modules/esm/module_job.js:42:21)
error Command failed with exit code 1.
```
node是v12版本

**Comment by buxuku** [comment]
node 12 版本已经太老了，请升级到 14.8 以上的版本以使用 await 的特性。如果你需要保留 12 版本的使用，建议可以使用 nvm 来管理 node 版本。

**Comment by winglight** [comment]
> node 12 版本已经太老了，请升级到 14.8 以上的版本以使用 await 的特性。如果你需要保留 12 版本的使用，建议可以使用 nvm 来管理 node 版本。

原来如此，我还以为12挺新的。。。

**Comment by winglight** [comment]
还有个问题，我想关闭翻译的时候，发现并没有明确的配置，只能不配置具体的翻译提供商信息，结果造成每个wav文件处理都报翻译错误

**Comment by buxuku** [comment]
```js
export const translateServiceProvider = 0;
```
即可关闭翻译功能。抱歉，文档我没有描述清楚，我接更新一下文档
